server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  mvc:
    view:
      prefix: /views/
      suffix: .html
      
  datasource:
    url: jdbc:h2:~/db/EWP
    driver-class-name: org.h2.Driver
    username: sa
    password:
    
  h2:
    console:
      path: /h2-console
      enabled: true
      
  sql:
    init:
      mode: always
      