server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true


spring:
  mvc:
    static-path-pattern: /static/**
      
  datasource:
    url: jdbc:h2:~/db/EWP
    driver-class-name: org.h2.Driver
    username: sa
    password:
    
  h2:
    console:
      path: /h2-console
      enabled: true
   
  thymeleaf:
    prefix: classpath:/views/
    suffix: .html